[project]
name = "lm-links-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.2.4",
    "pandas>=2.2.3",
    "typer>=0.15.2",
]
